baseURL: 'https://yekaiwu.github.io/'
title: 'Wu Yekai — Software Engineer'

defaultContentLanguage: en
enableRobotsTXT: true
enableEmoji: true
disableAliases: true
disableKinds: [taxonomy, term]

outputs:
  home: [HTML, RSS]
